### ISSUE TITLE
JsonSchemaOptions

### ISSUE THREAD

**Issue by andrzejwiech** [mbknor/mbknor-jackson-jsonSchema#102]
JsonSchemaOptions annotation does not work for me. I added it on method:

```
@JsonSchemaOptions.Item(name ="myname", value = "myvalue")
```
No attribute was generated for me. Could do it over @JsonSchemaInject though. Am I doing it wrong?

**Comment by mbknor** [comment]
Have you looked at how it is used in this test?

Annotated code:
https://github.com/mbknor/mbknor-jackson-jsonSchema/blob/master/src/test/scala/com/kjetland/jackson/jsonSchema/testDataScala/UsingJsonSchemaOptions.scala

And the test asserting that it works is here:
https://github.com/mbknor/mbknor-jackson-jsonSchema/blob/master/src/test/scala/com/kjetland/jackson/jsonSchema/JsonSchemaGeneratorTest.scala#L1252

**Comment by mbknor** [comment]
Closing due to lack of feedback from @andrzejwiech who submitted the issue
