### ISSUE TITLE
Enums repeated over and over, any alternative?

### ISSUE THREAD

**Issue by benson-basis** [mbknor/mbknor-jackson-jsonSchema#11]
Is there any way to get Java enums to turn into some sort of top-level item? I get the same long enumeration over and over in the schema.

"script": {
          "type": "string",
          "enum": [
            "Dsrt",
            "Bamu",
            ...
            }
There are many items in the list, and it turns up in my schema many times.

The order is also rather randomized, FWIW.

**Comment by mbknor** [comment]
I do not know of any way to 'point' to the same enum-list many times in a schema.
If you know how, please provide me with link to docs and example-schema.

Can you be more precise about the randomized order? is it random in the generated schema?
What order would you expect? Can you create example?
