### ISSUE TITLE
Feature request: leverage defaultValue of @JsonProperty in place of @JsonSchemaDefault

### ISSUE THREAD

**Issue by itzg** [mbknor/mbknor-jackson-jsonSchema#117]
Currently I find that I have to declare a field's default three ways, but it sure would be nice to get that down to two since the `defaultValue` of `@JsonProperty` is always going to be exactly the same string as `value` of `@JsonSchemaDefault`, such as:

```java
  @JsonSchemaDefault("true")
  @JsonProperty(defaultValue = "true")
  boolean totalcpu = true;
```

I would like to be able to use just:
```java
  @JsonProperty(defaultValue = "true")
  boolean totalcpu = true;
```

with a resulting schema:
```json
        "totalcpu": {
          "type": "boolean",
          "default": true
        },
```

**Comment by mbknor** [comment]
Included in version 1.0.38 released just now. It is on its way to maven central
