### ISSUE TITLE
Schema mostly disappears due to polymorphism annotations

### ISSUE THREAD

**Issue by benson-basis** [mbknor/mbknor-jackson-jsonSchema#13]
The schema does not descend into the contents of this map; it does not include BaseAttribute and its subclasses. If the annotations are not present, then the schema includes all of that.

```
    @JsonTypeInfo(use = JsonTypeInfo.Id.CUSTOM, include = JsonTypeInfo.As.PROPERTY, property = "type")
    @JsonTypeIdResolver(DmTypeIdResolver.class)
    public abstract Map<String, BaseAttribute> getAttributes();
```

**Comment by mbknor** [comment]
Can you place attache the follwoing, for me to be able to reproduce and find solution:

Class that has this map with annotations.
Example of how you would expect the schema to be generated.
And example json which complies both with schema and the Class.

**Comment by mbknor** [comment]
I think it is impossible to create a json schema representing something as free as a map.
