### ISSUE TITLE
Question: Is this the right module for me?

### ISSUE THREAD

**Issue by mariusheil** [mbknor/mbknor-jackson-jsonSchema#16]
Hi,

I am posting this because I have been evaluating a number of JsonSchemaGenerators for Java. Yours seems to be nicely written, supports draft-v4 and uses javax Annotations together with Jackson, which is perfect. Only problem is that it was written using Scala. Yesterday I got mixed Scala and Java compilation working after crashing Eclipse for hours because of the Scala integration.
I started with a simple test object like this:
public class TestJson {
	public int test = 45;
}
and I wondered why none of the JsonSchema Generators will output the "default" value of 45. I tryed to add this, but I guess I have to learn a little Scala first...
I think I might have to edit your module in a different project and will then import the artifact with maven to easen the workflow a little.

**Comment by mbknor** [comment]
maybe.. It depends :)

**Comment by mariusheil** [comment]
ok, I updated my previous question, GitHub is a little sensitive with the Enter Key :-)

**Comment by mbknor** [comment]
Even though mbknor-jackson-jsonSchema is written in scala, you do not need to use it.
Just add it as a maven-dependency to your java project and use it as described here: 
https://github.com/mbknor/mbknor-jackson-jsonSchema#code---using-java


When it comes to the default value, I do not think I have implemented "extracting" default-values yet.
Please add a new issue describing the "problem" and how you would expect the schema to look like.

**Comment by mariusheil** [comment]
Thanks, yes, I added it as a Maven dependency first, but I decided that I will probably have to modify or extend some bits. I'll open a new issue.
