### ISSUE TITLE
"format": "date" is used for java.time.LocalDate

### ISSUE THREAD

**Issue by pavelfomin** [mbknor/mbknor-jackson-jsonSchema#19]
For a field with type `java.time.LocalDate` a corresponding schema definition is generated as
```
		"dateOfBirth": {
			"type": "string",
			"format": "date"
		}
```
I like that `date` and `date-time` are treated differently but, unfortunately, `"format": "date"` is not listed as a [defined format of the json schema](http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3), only `date-time` is. As a result, per json schema spec, `If the type of the instance to validate is not in this set, validation for this format attribute and instance SHOULD succeed.` This makes the custom format `date` not very useful for validation unless a validator supports this specific custom format. Similarly, `json schema -> code` generators like [jsonSchema2Pojo](www.jsonschema2pojo.org/) are going to ignore this custom format.

Should `java.time.LocalDate` use `"format": "date-time"` by default? If a custom format attribute like `date` is desired then `@JsonSchemaFormat(value = "date")` can be used.

Version used: `com.kjetland:mbknor-jackson-jsonschema_2.11:1.0.9`.

**Comment by mbknor** [comment]
Hi,

First of all; Thanks for your interest in this project.

I'm not sure how to handle your request.
If you don't focus on the json-schema-spec, then "date" is a more correct representation of "LocalDate". "date-time" says that it also should include the time-part.

When using https://github.com/jdorn/json-editor#format to generate gui, then "date" correctly maps to the html5-date-picker.

One Idea could be to make this configurable:

https://github.com/mbknor/mbknor-jackson-jsonSchema/blob/master/src/main/scala/com/kjetland/jackson/jsonSchema/JsonSchemaGenerator.scala#L97

Then you could achieve the mapping of your desire.

What do you think?

**Comment by pavelfomin** [comment]
External mapping configuration for types would be great to have! Thanks for looking into this!

**Comment by pavelfomin** [comment]
Awesome! Thanks for adding this.
