### ISSUE TITLE
Question: Is is possible to have sub-objects without $ref?

### ISSUE THREAD

**Issue by mariusheil** [mbknor/mbknor-jackson-jsonSchema#20]
Hi,

just a short question because I wasn't able to find out if the generator is configurable to support including objects without using definitions and $ref.
Because I am trying to integrate it with angular-schema-form which currently does not support $ref and definitions.

**Comment by mbknor** [comment]
I do not thing this is supported

**Comment by benkeil** [comment]
Would be also required for Kubernetes when generating a CRD.
