### ISSUE TITLE
Preserve Enum values order

### ISSUE THREAD

**Issue by roee88** [mbknor/mbknor-jackson-jsonSchema#21]
The order of enum values is not preserved, due to the use of a set in the implementation.

Note that com.fasterxml.jackson.module.jsonSchema keeps the order intact, which is useful for enums representing days, months, etc.

**Comment by mbknor** [comment]
I've tested this and it looks like it is preserving the order.

When generating schema for this enum:
`
public enum MyEnum {
    C,B,A
}
`
We get this schema:

`
    "myEnum" : {
      "type" : "string",
      "enum" : [ "C", "B", "A" ]
    }
`

**Comment by roee88** [comment]
I generated a schema for a class holding a org.threeten.bp.Month (I believe it will be the save with the java8 Month as well). The order was not preserved. I changed asSet to asArray to fix that.

**Comment by mbknor** [comment]
If you can provide example code that show this problem, I'll reopen the ticket

**Comment by roee88** [comment]
Try the following:
```java
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.kjetland.jackson.jsonSchema.JsonSchemaGenerator;

import org.junit.Test;

public class TestBug {
    enum Month {
        JANUARY,
        FEBRUARY,
        MARCH,
        APRIL,
        MAY,
        JUNE,
        JULY,
        AUGUST,
        SEPTEMBER,
        OCTOBER,
        NOVEMBER,
        DECEMBER
    }

    @Test
    public void test() {
        ObjectMapper mapper = new ObjectMapper();
        JsonSchemaGenerator generator = new JsonSchemaGenerator(mapper);
        try {
            String x = mapper.writerWithDefaultPrettyPrinter()
                    .writeValueAsString(generator.generateJsonSchema(Month.class));
            System.out.println(x);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }

    }
}
```

It outputs 
```json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "Month",
  "type" : "string",
  "enum" : [ "DECEMBER", "APRIL", "JULY", "SEPTEMBER", "JUNE", "FEBRUARY", "OCTOBER", "AUGUST", "NOVEMBER", "MARCH", "MAY", "JANUARY" ]
}
```

**Comment by mbknor** [comment]
Thanks. I'll look into it
