### ISSUE TITLE
@JsonPropertyDescription is not implemented?

### ISSUE THREAD

**Issue by ratulm** [mbknor/mbknor-jackson-jsonSchema#22]
It appears that @JsonPropertDescription is not implemented?

I have this class:
   public class Shape {
      @JsonPropertyDescription("this is name")
      public String name;
   }

The output of jackson-modeule-jsonSchema:
{
  "type" : "object",
  "id" : "urn:jsonschema:org:batfish:client:Client:Shape",
  "properties" : {
    "name" : {
      "type" : "string",
      "description" : "this is name"
    }
  }
}

The output of mbknor-jackson-jsonSchema:
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "Shape",
  "type" : "object",
  "additionalProperties" : false,
  "properties" : {
    "name" : {
      "type" : "string"
    }
  }
}

Is this something that is on your todo (soon) list?

**Comment by mbknor** [comment]
I did not know of that one :)

Instead I've added my own @JsonSchemaDescription and @JsonSchemaTitle.

But it sure looks like @JsonPropertDescription should also be supported.

Can you work with the two other already implemented annotations for now?

**Comment by ratulm** [comment]
ok, will do. thanks.

two questions:
 1) what is the difference between @JsonSchemaDescription and @JsonSchemaTitle?
 2) i annotated a class with @JsonSchemaTitle  but still get its title field as null. is that expected?

**Comment by mbknor** [comment]
Both @JsonSchemaDescription and @JsonSchemaTitle can be annotated on both classes and properties.

This is tested in this test: https://github.com/mbknor/mbknor-jackson-jsonSchema/blob/master/src/test/scala/com/kjetland/jackson/jsonSchema/JsonSchemaGeneratorTest.scala#L508

It produces the following schema:
```json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "Pojo using format",
  "type" : "object",
  "additionalProperties" : false,
  "format" : "grid",
  "description" : "This is our pojo",
  "properties" : {
    "emailValue" : {
      "type" : "string",
      "format" : "email",
      "description" : "This is our email value",
      "title" : "Email value"
    },
    "choice" : {
      "type" : "boolean",
      "format" : "checkbox"
    },
    "dateTime" : {
      "type" : "string",
      "format" : "date-time"
    },
    "dateTimeWithAnnotation" : {
      "type" : "string",
      "format" : "text"
    }
  }
}
```
