### ISSUE TITLE
Improved "location-info" in error messages

### ISSUE THREAD

**Issue by ratulm** [mbknor/mbknor-jackson-jsonSchema#26]
When using the module on a complex set of classes, I get the following exception/warning messages:
        
        java.lang.Exception: We only support polymorphism using jsonTypeInfo.use == JsonTypeInfo.Id.NAME

        [main] WARN com.kjetland.jackson.jsonSchema.JsonSchemaGenerator - Not able to generate jsonSchema-info for type: [simple type, class java.lang.Object] - probably using custom serializer which does not override acceptJsonFormatVisitor

It'll be helpful if responsible class names were printed.  In the first case, printing "ac" does the trick. (I have a local change that I can push if you give me commit rights.)  In the second case, I was not sure what the fix is.

Thanks.

**Comment by ratulm** [comment]
The pull request fixes the first type of error message. I am not sure what to do about the second one. I've seen it occur when a class is empty (no properties).

**Comment by mbknor** [comment]
A better way would be to "keep track of" the "path", so that when an error occures, we can include that the error happend on "/propertyA/propertyB/"

**Comment by mbknor** [comment]
Closing issue due to lack of feedback/intereset
