### ISSUE TITLE
Add support for JsonTypeInfo.Id.CLASS

### ISSUE THREAD

**Issue by ratulm** [mbknor/mbknor-jackson-jsonSchema#27]
The code currently supports only JsonTypeInfo.Id.NAME 

        if ( jsonTypeInfo.use != JsonTypeInfo.Id.NAME) throw new Exception("We only support polymorphism using jsonTypeInfo.use == JsonTypeInfo.Id.NAME")

I have classes that use JsonTypeInfo.Id.CLASS and running the code on them after commenting the line above seems to do the right thing. 

Why does the requirement exist and can it be loosened to include JsonTypeInfo.Id.CLASS?

**Comment by ratulm** [comment]
I submitted a pull request for this. I hope this fix works. Let me know if you'd some modifications.

**Comment by mbknor** [comment]
Since the current codebase only explicit supports JsonTypeInfo.Id.NAME, I've added the exception to make clear that other jsonTypeInfo.use are not supported.

I'll look into adding support for JsonTypeInfo.Id.CLASS

**Comment by andrii-NIX** [comment]
Hi, 

Could you please also add support for `JsonTypeInfo.As.EXISTING_PROPERTY`?

Currently Spring DataRest doesn't support `JsonTypeInfo.As.PROPERTY`, as a workaround custom field could be created.
But if using it with together with PROPERTY then two "type" fields are generated when serializing with ObjectMapper, so having EXISTING_PROPERTY will solve the issue.

Thanks.

**Comment by mbknor** [comment]
@andrii-NIX : I've created a seperate ticket for EXISTING_PROPERTY: #36

**Comment by mbknor** [comment]
Fixed in https://github.com/mbknor/mbknor-jackson-jsonSchema/commit/de5425e8de104d653b5113431cbd75458fb4cfc2

**Comment by mbknor** [comment]
This fix has just been released in version 1.0.18 which now is on the way to the public sonatype repo

**Comment by ratulm** [comment]
Thanks! I'll give it a try soon.
