### ISSUE TITLE
JsonFormatVisitor.format(...) not recognized

### ISSUE THREAD

**Issue by falco467** [mbknor/mbknor-jackson-jsonSchema#3]
Hi!

I see you have started to implement your own Annotations to set a "format": specifier. - The jackson JsonFormatVisitor already has a method to set the Format, with an Enum of Standard-Formats. But this seems to be currently ignored by the jsonSchema,

Example:

	new JsonSerializer< LocalDate >() {
		public void serialize( final LocalDate v, final JsonGenerator gen, final SerializerProvider sp ) {
			gen.writeString( v.toString() );
		}
		
		public void acceptJsonFormatVisitor( final JsonFormatVisitorWrapper visitor, final JavaType typeHint ) {
			visitor.expectStringFormat( typeHint ).format( JsonValueFormat.DATE );
		}
	}

Expected output would be:
`"format" : "date"`

**Comment by mbknor** [comment]
I'll look into it..

I still need a way to support custom format-strings..

E.g: To support GUIs using https://github.com/jdorn/json-editor, I need more format-options than what is specified in JsonValueFormat.

**Comment by falco467** [comment]
The fix is working :+1:
