### ISSUE TITLE
All class hierarchy properties are pushed down to the child

### ISSUE THREAD

**Issue by grkosick** [mbknor/mbknor-jackson-jsonSchema#35]
I have the following class hierarchy:

`public abstract class ClassHierarchy {

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
    @JsonSubTypes({
            @JsonSubTypes.Type(value = Parent1.class, name = "Parent 1"),
            @JsonSubTypes.Type(value = Parent2.class, name = "Parent 2")
    })
    public static class AbstractParent {

        @Getter
        @Setter
        private String abstractParentName;
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
    @JsonSubTypes({ @JsonSubTypes.Type(value = ChildOfParent1.class, name = "Child Of Parent 1") })
    public static class Parent1 extends AbstractParent {

        @Getter
        @Setter
        private String parent1Description;
    }

    public static class ChildOfParent1 extends Parent1 {

        @Getter
        @Setter
        private Integer childOfParentOneSize;

        @Getter
        @Setter
        private Status childOfParentOneStatus;
    }

    public static class Parent2 extends AbstractParent {

        @Getter
        @Setter
        private String parent2description;

        @Getter
        @Setter
        private Status parent2Status;
    }

    public static enum Status {

        ONLINE,
        AWAY,
        OFFLINE;
    }

}`

The generated schema is: 
```
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "Abstract Parent",
  "oneOf" : [ {
    "$ref" : "#/definitions/Parent1"
  }, {
    "$ref" : "#/definitions/Parent2"
  } ],
  "definitions" : {
    "Parent1" : {
      "oneOf" : [ {
        "$ref" : "#/definitions/ChildOfParent1"
      } ]
    },
    "ChildOfParent1" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "type" : {
          "type" : "string",
          "enum" : [ "Child Of Parent 1" ],
          "default" : "Child Of Parent 1"
        },
        "abstractParentName" : {
          "propertyOrder" : 1,
          "type" : "string",
          "title" : "Abstract Parent Name"
        },
        "parent1Description" : {
          "propertyOrder" : 2,
          "type" : "string",
          "title" : "Parent 1 Description"
        },
        "childOfParentOneSize" : {
          "propertyOrder" : 3,
          "type" : "integer",
          "title" : "Child Of Parent One Size"
        },
        "childOfParentOneStatus" : {
          "propertyOrder" : 4,
          "type" : "string",
          "enum" : [ "ONLINE", "AWAY", "OFFLINE" ],
          "title" : "Child Of Parent One Status"
        }
      },
      "title" : "Child Of Parent 1",
      "required" : [ "type" ],
      "options" : {
        "multiple_editor_select_via_property" : {
          "property" : "type",
          "value" : "Child Of Parent 1"
        }
      }
    },
    "Parent2" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "type" : {
          "type" : "string",
          "enum" : [ "Parent 2" ],
          "default" : "Parent 2"
        },
        "abstractParentName" : {
          "propertyOrder" : 1,
          "type" : "string",
          "title" : "Abstract Parent Name"
        },
        "parent2description" : {
          "propertyOrder" : 2,
          "type" : "string",
          "title" : "Parent 2description"
        },
        "parent2Status" : {
          "propertyOrder" : 3,
          "type" : "string",
          "enum" : [ "ONLINE", "AWAY", "OFFLINE" ],
          "title" : "Parent 2 Status"
        }
      },
      "title" : "Parent 2",
      "required" : [ "type" ],
      "options" : {
        "multiple_editor_select_via_property" : {
          "property" : "type",
          "value" : "Parent 2"
        }
      }
    }
  }
}
```

I am going to create a custom ui form per each class hierarchy from provided schema

Is it possible to show the property of the class Parent1 which is: 'parent1Description'

**Comment by mbknor** [comment]
hi,

I'm not sure I understand your problem. Could you please show me how you would expect/like the generated schema to look like?

**Comment by mbknor** [comment]
Closing due to lack of more info from issue author
