### ISSUE TITLE
support JsonTypeInfo.As.EXISTING_PROPERTY

### ISSUE THREAD

**Issue by mbknor** [mbknor/mbknor-jackson-jsonSchema#36]
From @andrii-NIX originally posted on #27:

Hi,

Could you please also add support for JsonTypeInfo.As.EXISTING_PROPERTY?

Currently Spring DataRest doesn't support JsonTypeInfo.As.PROPERTY, as a workaround custom field could be created.
But if using it with together with PROPERTY then two "type" fields are generated when serializing with ObjectMapper, so having EXISTING_PROPERTY will solve the issue.

Thanks.

**Comment by mbknor** [comment]
@andrii-NIX: I think I've fixed the problem with JsonTypeInfo.As.EXISTING_PROPERTY. Could you be so kind to test it, or even better: Help me create test-case-classes using EXISTING_PROPERTY ala this existing test-case-data: https://github.com/mbknor/mbknor-jackson-jsonSchema/blob/master/src/test/scala/com/kjetland/jackson/jsonSchema/testData/polymorphism1/Parent.java

**Comment by mbknor** [comment]
The maybe-fix is included in version 1.0.18 which now is on the way to the public sonatype repo

**Comment by andrii-NIX** [comment]
Hi, thanks for the fast reaction. I've added test case, please check #37

**Comment by mbknor** [comment]
Fixed in 1.0.18
