### ISSUE TITLE
Java Generics parameterized classes are defined as one.

### ISSUE THREAD

**Issue by DALDEI** [mbknor/mbknor-jackson-jsonSchema#39]
Definately an edge case ... but it is possible I belive.

I have a class like this:

class Config<T extends Enum> {
  T type;
  Integer iCommon;
 String  sCommon;
};

class MyConfig {
   Config<EnumA>  aConfig;
  Config<EnumB>  bConfig;
..
}

( plus all the normal annoations )

THe result is a schema that defines aConfig, bConfig ... as identical, 

    "aConfig" : { "$ref" : '#/definitions/Config' }

    "bConfig" : { "$ref" : '#/definitions/Config' }

I was expectecting that .. what I didnt expect was that "Config" pulled in the correct enum values 
  from EnumA .

    "type" : { 
       "type" : "string" , 
      "enum" : [ "all","the","right","enums","from","EnumA" ]
..

Not bad !
Suggestions besides "Dont do that ?" 
derived classes maybe ? 
     class ConfigA extends Config<EnumA> ; .... 

Ideally the generics should be recognized as distinct JSON types -- for this purpose atleast.
( debatable in Java if they are different types or not -- yes at compile , sorta, no at runtime).

Is there a way to abuse an existing annotation ?

**Comment by mbknor** [comment]
Hi,

I'm not completely following this..

I think you have to show the "problem" with:

- complete class-declarations
- example of generated schema
- suggestions about what is wrong with the generated schema

-Morten

**Comment by mbknor** [comment]
Closing due to lack of more info from issue-author

**Comment by tomashaber** [comment]
Hi,

I think I have a similar issue as @DALDEI 
I want to generate a JSON schema for the Value class below

```
class Value {
Box<String> boxA;
Box<Integer> boxB;
}
class Box<T> {
 T value;
}
```
If I generated a schema from this, it would contain only one definition of a Box schema and this schema would only permit a Box with a String value.

What I would expect is to have two schemas for the Box class, one for a Box with String and one for a Box with an Integer.
I resolved this in my fork of your library and it's good enough for my use case. If you're interested please see:
https://github.com/tomashaber/mbknor-jackson-jsonSchema/commit/54567afe4bc0fafeb74075752f9bb0c400d9eee3
