### ISSUE TITLE
@JsonProperty support

### ISSUE THREAD

**Issue by yasargil** [mbknor/mbknor-jackson-jsonSchema#4]
Hi

I looks like @JsonProperty is not supported. Properties annotated with it are no appearing in the schema. I need it to rename the property.

**Comment by yasargil** [comment]
I did look in to the issue and found as soon as the @JsonProperty required is true the property is not added  to the schema. Probably because the overriden methods from JsonObjectFormatVisitor are not all implemented. In this case the method roperty(writer: BeanProperty) is called.


This works:
`
@NotNull
@JsonProperty(value=FileFinder.CONFIG_BASE_KEY)
private final String var;
`

This does not
`
@JsonProperty(value=FileFinder.CONFIG_BASE_KEY, required=true)
private final String modelsPath;
`

**Comment by mbknor** [comment]
Thanks a lot for the detailed info. I'll look into it.

-morten
