### ISSUE TITLE
JsonTypeInfo WRAPPER_OBJECT support

### ISSUE THREAD

**Issue by RobBrazier** [mbknor/mbknor-jackson-jsonSchema#43]
Would it be possible to support JsonTypeInfo.WRAPPER_OBJECT?

I've mocked up a sample object and schema of what it could look like below. 

Are there any reasons to why you didn't originally implement support for WRAPPER_OBJECT, or was it just because there seems to be quite a bit more to do compared with PROPERTY and EXTERNAL_PROPERTY?

I'm happy to have a look into this if there are no objections

```
{
  "id": "1",
  "person": [
    {
      "Person": {
        "firstName": "first",
        "lastName": "last"
      }
    }
  ]
}

```
```
{
"$schema" : "http://json-schema.org/draft-04/schema#",
  "type" : "object",
  "additionalProperties" : false,
  "properties" : {
    "id" : {
      "type" : "string"
    },
    "person" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/definitions/PersonWrapper"
      },
      "minItems": 1,
      "maxItems": 1
    }
  },
  "definitions" : {
    "PersonWrapper": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Person": {
          "$ref": "#/definitions/Person"
        }
      }
    },
    "Person" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "firstName" : {
          "type" : "string"
        },
        "lastName" : {
          "type" : "string"
        }
      }
    }
  }
}
```

**Comment by mbknor** [comment]
The reason for not implementing support for it, is because I have not used it before.

Can you also add example Java or Scala source using this annotation going along with your example?

-Morten

**Comment by RobBrazier** [comment]
I actually got the schemas wrong in the original description.

Updated Schemas and classes (there are multiple ways to wrap the object, depending on where the annotation is):
Single class: https://gist.github.com/RobBrazier/dfec17fc2418c6390e5e3968f6ea4f65

Multiple classes (on abstract class/interface): https://gist.github.com/RobBrazier/dfec17fc2418c6390e5e3968f6ea4f65

Unfortunately I couldn't think of an example that could be used for both, so they are slightly different

**Comment by mbknor** [comment]
Thanks..

I now understand what you need.
For the time being, I am not going to spend time to implement this, but feel free to send PR.
If you do so, I think it would be more easy to integrate it if you do not use the "PersonWrapper -> Person"-apporach.

I think it is more easy to kind of inject the PerseonWrapper-structure "inline".. Just an idea.

**Comment by mbknor** [comment]
Closing this issue due to lack of feedback from @RobBrazier
