### ISSUE TITLE
Add enumClass for Enum attribute types

### ISSUE THREAD

**Issue by mafavale** [mbknor/mbknor-jackson-jsonSchema#45]
I need to have the associated enum class for enum values, not just the values of the enum.
Let's suppose i have this:

```
package demo;
public enum Type { 
    A,
    B
}

package demo;
public class DemoBean {
    private Type type;
}
```

The JSON Schema resulting on this would be:

```
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "Demo Bean",
  "type" : "object",
  "additionalProperties" : false,
  "properties" : {
    "type" : {
      "type" : "string",
      "enum" : [ "A", "B" ]
    }
  }
}
```
I would like to have this result instead: 
```
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "Demo Bean",
  "type" : "object",
  "additionalProperties" : false,
  "properties" : {
    "type" : {
      "type" : "string",
      "enum" : [ "A", "B" ],
      "enumClass": "demo.Type"
    }
  }
}
```
Is there any configuration i have missing to do this or workaround i can do?

Thank you.

**Comment by mbknor** [comment]
Since what you're asking for is not standard Json-Schema-syntax, I guess the easiest way to achieve it is using the JsonSchemaInject-annotation.

Something like this:

```
public class DemoBean {

    @JsonSchemaInject( json = "{\"enumClass\": \"demo.Type\"}")
    private Type type;
}
```

Would that work for you?

**Comment by mafavale** [comment]
Thanks for the quick response! 

Yes, that works, although, it would be much better if i can inject that at a class level (or in an enum level in this case) because i have a lot of classes with enum attributes and it would save a lot of time and code, i tried it but that doesn't work. I see that the annotation JsonTypeInject supports Type, but i can't figure out how to make it work.

**Comment by mbknor** [comment]
I had a quick look at the code and it looks like it could work to add the functionality you ask for in the following method:

https://github.com/mbknor/mbknor-jackson-jsonSchema/blob/master/src/main/scala/com/kjetland/jackson/jsonSchema/JsonSchemaGenerator.scala#L330

The param _type: JavaType will be the enum type and we could look for JsonTypeInject-annotation on it..

I'll have a look at it when I have more time available

**Comment by mbknor** [comment]
Fixed in "Now also finding @JsonSchemaInject-annotation on Enum-types (Fix #45)" (https://github.com/mbknor/mbknor-jackson-jsonSchema/commit/e62084a17c7c16d31f7e5bf2c3942a2047459d1f)

**Comment by mbknor** [comment]
Version 1.0.23 has been released and is on its way to a maven repo near you :)

**Comment by mafavale** [comment]
Wow, that's great! Thanks a lot!
