### ISSUE TITLE
JSON Views support (workaround in description)

### ISSUE THREAD

**Issue by jordihs** [mbknor/mbknor-jackson-jsonSchema#46]
Just started to use this project and I could not find an explicit way to use views when generating a schema. 
i.e. @JsonView(Views.MyView.class)
This is most helpful for an API for internal/external clients that will receive different outputs out of the same class, by calling different service endpoints. 
So if I could use this feature I would be able to distribute different schemas out of a single response class for each designed client. 
Now, I have found a solution to have this working by fiddling with the ObjectMapper API. This kind of make it not really necessary to modify the jsonSchema code. I am sort of new with Github so rather than an issue this might be more like an advice post. Hence I apologize beforehand if opening an issue is of any distress for you. 
Anyway, here is how you do it: 

```
// Our vanilla ObjectMapper
ObjectMapper objectMapper = new ObjectMapper();
		
// Disabling default View so only the stuff that matters is output
objectMapper.disable(MapperFeature.DEFAULT_VIEW_INCLUSION);
	    
// And the trick: grab the serializationConfig and define the desired view
objectMapper.setConfig(objectMapper.getSerializationConfig().withView(Views.MyView.class));
	    
// Then, proceed as usual. Only fields and classes annotated with MyView will appear in the schema
JsonSchemaGenerator generator = new JsonSchemaGenerator(objectMapper);
```

Since this is simple enough, you might want to consider adding the example to the documentation and/or close the issue so that at least people looking for the feature can read it here. 

Cheers and thanks for sharing your very useful code.

**Comment by mbknor** [comment]
Ahh.. Thanks a lot!
This should definitely be added to the docs.

If you want some github-pullrequest-experience, feel free to add it for me :)

**Comment by jordihs** [comment]
Done, pull request underway. Hope the style is to your liking. Do review the Scala sample since I'm quite a noob in that language...
