### ISSUE TITLE
Support JavaType in addition to Class<?> for generateJsonSchema

### ISSUE THREAD

**Issue by jekkel** [mbknor/mbknor-jackson-jsonSchema#47]
Currently only `Class<?>` is supported as argument to the schema generator. Internally I saw it's delegated eventually to jackson as `JavaType`. Directly providing an overload for generation of the schema of a `JavaType` would allow schema generation for generic classes (`ParameterizedType`).

**Comment by jekkel** [comment]
Wow that was fast!

**Comment by mbknor** [comment]
Fix included in version 1.0.24 which I released yesterday evening (Norway time)
