### ISSUE TITLE
What of anyOf and allOf JSON Schema features?

### ISSUE THREAD

**Issue by nemonik** [mbknor/mbknor-jackson-jsonSchema#51]
I see support for oneOf, but what of `anyOf` and `allOf` draft 4 constructs?

**Comment by mbknor** [comment]
Hi.

I'm not sure anyOf would work in context of deserializing it into Java/Scala classes.
Same goes with allOf.

Please enlighten me

**Comment by mbknor** [comment]
Closing this (for now) due to lack of more info.
