### ISSUE TITLE
Not correctly resolving subTypeName for polymorphism if not using @JsonTypeName

### ISSUE THREAD

**Issue by mattdehring** [mbknor/mbknor-jackson-jsonSchema#52]
I am using these settings on my base class:
`@JsonTypeInfo(include=JsonTypeInfo.As.PROPERTY, use=JsonTypeInfo.Id.NAME,property="type")`

I am getting this returned as the properties if I don't set a `@JsonTypeName`:
`"properties" : {
        "type" : {
          "type" : "string",
          "enum" : [ null ],
          "default" : null,
          "options" : {
            "hidden" : true
          }
        }`
When I do set a `@JsonTypeName("User")` like so I get what I expect:
`"properties" : {
        "type" : {
          "type" : "string",
          "enum" : [ "User" ],
          "default" : "User",
          "options" : {
            "hidden" : true
          }
        }`

**Comment by mbknor** [comment]
To figure this out, you have to show which classes you have and how they extend each other.

I also need the complete generated schema.

I guess it would be better if you created a test-case showing the problem.

**Comment by mbknor** [comment]
Since @mattdehring  is not supplying more info, I'm closing this issue for now. I'll re-open it if more info is supplied
