### ISSUE TITLE
Upgrade javax.validation to 2.0+

### ISSUE THREAD

**Issue by kog** [mbknor/mbknor-jackson-jsonSchema#53]
[JSR-380](https://www.jcp.org/en/jsr/detail?id=380) (Bean Validation 2.0) went live in August 2017, and contains a number of useful validation annotations. A human-readable summary of what's new is available at [beanvalidation.org](http://beanvalidation.org/news/2017/08/07/bean-validation-2-0-is-a-spec/). 

I'm using some of these annotations (particularly `@NotBlank` and `@NotEmpty`) for my domain model validation via Hibernate Validator, which means that I also need to combine annotations with `@NotNull` in order to generate correct schema. This causes some less than desirable behavior in that exactly which annotation gets tripped seems to be non-deterministic. 

I've got a PR for this change and some prototypes for generating schema for the aforementioned annotations. I figure I'd post an issue before going too far - no point in building code/test cases if folks don't want to upgrade. 

**Dependency Changes** 

- the build.sbt dependency on javax.validation:validation-api changes from `1.1.0.Final` to `2.0.1.Final`
- Neither version of the artifact has any transitive dependencies ([1.1.0.Final](https://mvnrepository.com/artifact/javax.validation/validation-api/1.1.0.Final), [2.0.1.Final](https://mvnrepository.com/artifact/javax.validation/validation-api/2.0.1.Final))

**Comment by mbknor** [comment]
thanks.

I've been on holiday but will take a look at this soon.

-Morten

**Comment by kog** [comment]
Yeah, figured you were probably out having a life as all people should. 

I've got a PR at https://github.com/mbknor/mbknor-jackson-jsonSchema/pull/54 and can get some of those annotations going if anyone else is interested. Do let me know if I can provide any details.

**Comment by mbknor** [comment]
Version 1.0.26 is released and on its way to maven central
