### ISSUE TITLE
additionalProperties not supported

### ISSUE THREAD

**Issue by Mart-Bogdan** [mbknor/mbknor-jackson-jsonSchema#57]
I have my POJO with annotations:
```
    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return additionalProperties != null
                ? additionalProperties
                : (additionalProperties = new LinkedHashMap<>());
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.getAdditionalProperties().put(name, value);
    }
```
Genrated JSON-Schema has: `"additionalProperties":false`  instead of true :-(

**Comment by mbknor** [comment]
When using @JsonAnyGetter/@JsonAnySetter, it impossible for Jackson (and mbknor-jackson-jsonSchema) to know what dataTypes you're accepting.

You could try to override the "additionalProperties"-flag using @JsonSchemaInject, or you could try top create a pull-request with the logic of setting additionalProperties = true, when @JsonAnySetter is used

**Comment by Mart-Bogdan** [comment]
> it impossible for Jackson (and mbknor-jackson-jsonSchema) to know what dataTypes you're accepting.
you mean for `patternProperties` ?

**Comment by mbknor** [comment]
I mean that you can try to force the flag to be set to true like this:

```Java
@JsonSchemaInject( json = "{\"additionalProperties\" : true}" )
public class MyPojo
```
