### ISSUE TITLE
Does this lib work correctly with Scala 2.12?

### ISSUE THREAD

**Issue by ranchoiver** [mbknor/mbknor-jackson-jsonSchema#61]
Trying to generate a schema for following case class:

```
case class Event(userId: String,
                             source: String,
                             destination: String)
```

Using the code from the examples:
```
    val objectMapper = new ObjectMapper
    val jsonSchemaGenerator = new JsonSchemaGenerator(objectMapper)
    val jsonSchema: JsonNode =
     jsonSchemaGenerator.generateJsonSchema(classOf[Event])
    objectMapper.writeValueAsString(jsonSchema)
```

Result:
`{"$schema":"http://json-schema.org/draft-04/schema#","title":"Event","type":"object","additionalProperties":false,"properties":{}}`

No fields from case class are generated in the resulting JSON schema.

Am I doing anything wrong?

**Comment by mbknor** [comment]
In order to use Jackson with Scala, you have to register the jackson-module-scala.
