### ISSUE TITLE
JSONSchemaInject - Defining parent node

### ISSUE THREAD

**Issue by AScully24** [mbknor/mbknor-jackson-jsonSchema#69]
First of, great library. It's been a pleasure to use.

The main issue I'm having is using @JSONSchemaInject to add form functionality that isn't supported yet (That I know if)

I am attempting to add support for "dependencies" for when the form is in a certain state, some fields will be hidden/shown.

My example follows this criteria:
 - If the enum value for "list" is "INPUT", I don't want any fields to display.
 - If the enum value for "list" is "OUTPUT", display "firstVal" number field
 - If the enum value for "list" is "RULE, display "secondVal" boolean field

However, I need to inject the json schema as a child of "properties", but I don't see any obvious way of doing this.

If this isn't available, could it be an optional parameter in JSONSchemaInject to define a parent?

NOTE: I'm aware that my JSON Schema may be... wrong, but all that being said, I still think this would be a useful feature,

JSON Schema to Inject
``` JSON
{
    "dependencies": {
        "list": {
            "oneOf": [
                {
                    "properties": {
                        "list": {
                            "enum": [
                                "INPUT"
                            ]
                        }
                    }
                },
                {
                    "properties": {
                        "list": {
                            "enum": [
                                "OUTPUT"
                            ]
                        },
                        "firstVal": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "firstVal"
                    ]
                },
                {
                    "properties": {
                        "list": {
                            "enum": [
                                "RULE"
                            ]
                        },
                        "secondVal": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "secondVal"
                    ]
                }
            ]
        }
    }
}
```

JAVA Class - 

MySupplier.class injects the above JSON into the generated schema. The "parent" field is an example of what could be implemented to inject JSON to certain locations.
``` Java
@JsonSchemaInject(jsonSupplier = MySupplier.class, parent="properties")
public class TestRule {

    public enum TestEnum {
        INPUT, OUTPUT, RULE
    }

    TestEnum list = TestEnum.INPUT;

    int firstVal;
    boolean secondVal;

    public TestEnum getList() {
        return list;
    }

    public void setList(TestEnum list) {
        this.list = list;
    }

    public int getFirstVal() {
        return firstVal;
    }

    public void setFirstVal(int firstVal) {
        this.firstVal = firstVal;
    }

    public boolean getSecondVal() {
        return secondVal;
    }

    public void setSecondVal(boolean secondVal) {
        this.secondVal = secondVal;
    }
}

```

**Comment by mbknor** [comment]
Too complicated feature-request. Please create PullRequest with sugested implementation if you are interested in getting it added.
