### ISSUE TITLE
@JsonSchemaDefault does not allow float values

### ISSUE THREAD

**Issue by anton-batylin** [mbknor/mbknor-jackson-jsonSchema#73]
Hi

@JsonSchemaDefault does not allow float values. It seems it tries to parse string as long:

https://github.com/mbknor/mbknor-jackson-jsonSchema/blob/8c42ea75aaf6dd4826638c9231780061b00d95d7/src/main/scala/com/kjetland/jackson/jsonSchema/JsonSchemaGenerator.scala#L485

Thanks.

**Comment by mbknor** [comment]
Fixed in https://github.com/mbknor/mbknor-jackson-jsonSchema/commit/a0aa0530be8285a15b7115c8173d7e1c306776f6

**Comment by mbknor** [comment]
Included in version 1.0.31 which is just released

**Comment by kascaks** [comment]
Hi
seems like this has been reintroduced again.
This does not work
`@JsonSchemaDefault("0.6")
private double value;`
https://github.com/mbknor/mbknor-jackson-jsonSchema/blob/e370f80d5dd20eb9396455ab2ddfd7083d0e25fb/src/main/scala/com/kjetland/jackson/jsonSchema/JsonSchemaGenerator.scala#L674
https://github.com/mbknor/mbknor-jackson-jsonSchema/blob/e370f80d5dd20eb9396455ab2ddfd7083d0e25fb/src/main/scala/com/kjetland/jackson/jsonSchema/JsonSchemaGenerator.scala#L703

**Comment by almson** [comment]
1.0.37 is the last version to work
