### ISSUE TITLE
Trouble with Java LocalDate

### ISSUE THREAD

**Issue by ctippin** [mbknor/mbknor-jackson-jsonSchema#76]
Hello,

I am having an issue with handling fields of type LocalDate.  The resulting json is treating like an object and not {"type" : "string", "format" : "date"} as I had hoped.

Test code:
`public class SchemaTest {

    public static void main(String[] args) throws JsonProcessingException {
        ObjectMapper objectMapper = new ObjectMapper();
        JsonSchemaGenerator jsonSchemaGenerator = new JsonSchemaGenerator(objectMapper );
        JsonNode jsonSchema = jsonSchemaGenerator.generateJsonSchema(TestSimple.class);

        String schema = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(jsonSchema);
        System.out.println(schema);
    }

    public static class TestSimple {
        @JsonProperty()
        private String s1;
        @JsonProperty()
        private LocalDate localDate1;
        @JsonProperty()
        private Date date1;

    }
}`

The resulting schema is : 
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "Test Simple",
  "type" : "object",
  "additionalProperties" : false,
  "properties" : {
    "s1" : {
      "type" : "string"
    },
    "localDate1" : {
      "$ref" : "#/definitions/LocalDate"
    },
    "date1" : {
      "type" : "integer",
      "format" : "utc-millisec"
    }
  },
  "definitions" : {
    "LocalDate" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "year" : {
          "type" : "integer"
        },
        "month" : {
          "type" : "string",
          "enum" : [ "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" ]
        },
        "era" : {
          "$ref" : "#/definitions/Era"
        },
        "dayOfYear" : {
          "type" : "integer"
        },
        "dayOfWeek" : {
          "type" : "string",
          "enum" : [ "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY" ]
        },
        "leapYear" : {
          "type" : "boolean"
        },
        "dayOfMonth" : {
          "type" : "integer"
        },
        "monthValue" : {
          "type" : "integer"
        },
        "chronology" : {
          "$ref" : "#/definitions/IsoChronology"
        }
      },
      "required" : [ "year", "dayOfYear", "leapYear", "dayOfMonth", "monthValue" ]
    },
    "Era" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "value" : {
          "type" : "integer"
        }
      },
      "required" : [ "value" ]
    },
    "IsoChronology" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "calendarType" : {
          "type" : "string"
        }
      }
    }
  }
}
Am I doing something wrong?

I am using the following version:
			<groupId>com.kjetland</groupId>
			<artifactId>mbknor-jackson-jsonschema_2.12</artifactId>
			<version>1.0.29</version>

**Comment by kog** [comment]
Jackson doesn't support the new `java.time` types out of the box. There are a set of modules for Java 8 support at https://github.com/FasterXML/jackson-modules-java8. You're going to want to register **_at least_** the `JavaTimeModule` on your `ObjectMapper`.

That'll get you support for the Java 8 time types, but remember that Jackson defaults to numeric timestamps by default. If you'd like strings as mentioned above, you're going to want to disable the `WRITE_DATES_AS_TIMESTAMPS` serialization feature on your object mapper (link: https://github.com/FasterXML/jackson-databind/wiki/Serialization-Features#datatype-specific-serialization). This will result in an ISO-8601 flavored string.

**Comment by ctippin** [comment]
Thank you!  That is exactly what I needed and I have verified that all is working as expected now.
