### ISSUE TITLE
Add support for `BigDecimal`

### ISSUE THREAD

**Issue by Hronom** [mbknor/mbknor-jackson-jsonSchema#79]
Please add support for converting `BigDecimal` and annotations `@DecimalMax` and `@DecimalMin` accordingly to add `minimum` and `maximum` in result JSON schema.

**Comment by Hronom** [comment]
Added pull request for this and also fix for default value.
Please can you provide an estimate about then this will be in maven central?

**Comment by mbknor** [comment]
Fixed in https://github.com/mbknor/mbknor-jackson-jsonSchema/commit/a0aa0530be8285a15b7115c8173d7e1c306776f6

**Comment by mbknor** [comment]
Included in version 1.0.31 which is just released

**Comment by Hronom** [comment]
Thanks, very appreciated for so fast pushing!
