### ISSUE TITLE
Support multiple types in the items of an array

### ISSUE THREAD

**Issue by AlexBroadbent** [mbknor/mbknor-jackson-jsonSchema#82]
There could be something already for this, but I cannot find something that gives the exact behaviour I am looking for.

After looking at some tests, the `classTypeReMapping` configuration property looks like it was doing something similar. Though this explicitly says that a base class can only be one of a given set. I am looking for something more flexible in that a single base class could be one of any given set per usage.

### Supported multiple types in draft-04

I have seen the schema supports specifying an ordered list of `items` for an `array`, such that the items in the list must be of the given types, in the [draft 4 spec](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#page-9). Such as:
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "My Test Class",
  "properties": {
    "list": {
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "items": [ 
        { "type": "string" }, 
        { "type": "number" } 
      ]
    }
  }
}
```
Valid input:    `{ "list": [ "foo", 5 ] }`
Invalid input: `{ "list": [ 13, false ] }`

### Use case

To map the above scenario into a Java project, I would have a base class:

```java
public class MyTestClass {

  @JsonProperty
  @Size(min = 2, max = 2)
  @JsonSchemaTitle("List")
  @JsonSchemaDescription("A list of two objects, of either 'string' or 'number' type")
  private List<Object> list;

  
  public List<Object> getList() {
    return list;
  }

}
```

The `Size` annotation will set the `minItems` and `maxItems` of the list. However, because there is no base class which only encompases a `String` or `Number` - I have to use `Object`. This means that the invalid scenario above would fail. _(Granted, we could create a specific class which only accepts a `String` or `Number` value and write a custom deserializer to fail on another type - but using the `JsonSchemaGenerator` to create the schema would not give us the desired output above)_

### Potential Solution

As stated before, I am not sure if there is a way to do this already, but perhaps an annotation for defining specific implementation classes within an `Array` would be a good solution.

Something like:

```java
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface JsonSchemaArrayItems {

  JsonSchemaArrayItem[] items() default {};

  public @interface JsonSchemaArrayItem {
    
    int index();

    Class<?> value();

  }

}
```

Which would give us the refactored class:

```java
public class MyTestClass {

  @JsonProperty
  @Size(min = 2, max = 2)
  @JsonSchemaTitle("List")
  @JsonSchemaDescription("A list of two objects, of either 'string' or 'number' type")
   @JsonSchemaArrayItems(items = {
        @JsonSchemaArrayItem(index = 0, value = String.class),
        @JsonSchemaArrayItem(index = 1, value = Number.class),
    })
  private List<Object> list;

  
  public List<Object> getList() {
    return list;
  }

}
```

Generating a schema for `MyTestClass` would generate something like:

```json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "type" : "object",
  "properties": {
    "list": {
      "type": "array",
      "title": "List",
      "description": "A list of two objects, of either 'string' or 'number' type",
      "minItems": 2,
      "maxItems": 2,
      "items": [
        { "type": "string" },
        { "type": "number" }
      ]
    }
  }
}
```

**Comment by AlexBroadbent** [comment]
To update the above "potential solution" with what I pushed:

### JsonSchemaArrayFilter

The annotation contains a list of classes permitted to be in an array; therefore, the annotation should be placed on a collection variable (such as a `List` or `Array`). This uses generics to restrict which implementations of a base class can be used within a collection.

### Use case

A base class:
```java
@JsonTypeInfo(use = Id.NAME, include = As.EXISTING_PROPERTY, property = "name")
@JsonSubTypes({
  @JsonSubTypes.Type(name = "cat", value = Cat.class),
  @JsonSubTypes.Type(name = "fox", value = Fox.class),
  @JsonSubTypes.Type(name = "dog", value = Dog.class),
})
public abstract class Animal {
  public abstract String name();
  public abstract String noise();
}
```

Cat class:
```java
public class Cat extends Animal {
  public String name() { return "cat"; }
  public String noise() { return "meow"; }
}
```

Dog class:
```java
public class Cat extends Animal {
  public String name() { return "dog"; }
  public String noise() { return "woof"; }
}
```

Fox class:
```java
public class Fox extends Animal {
  public String name() { return "fox"; }
  public String noise() { return "bark"; }
}
```


Now we have our base models in place, we can have a class which contains a list of domestic and wild animals:
```java
public class Animals {
  public List<Animal> domesticAnimals;
  public List<Animal> wildAnimals;
}
```

Creating a JSON schema for `Animals` will produce an array of `Animal` where the items will be `oneOf` a `cat`, `fox`, or `dog` for both `domesticAnimals` and `wildAnimals`.

We only want `dog` and `cat` objects in the `domesticAnimals` list and only `fox` objects in the `wildAnimals` list.


### Solution

 This can be done by adding the `@JsonSchemaArrayFilter` annotation onto the variables, such that:

```java
public class Animals {

  @JsonSchemaArrayFilter({Cat.class, Dog.class,})
  public List<Animal> domesticAnimals;

  @JsonSchemaArrayFilter({Fox.class,})
  public List<Animal> wildAnimals;

}
```

Generating a JSON schema of `Animals` now will produce a an array of `Animal` where the items for `domesticAnimals` will be `oneOf` a `cat` or `dog`, and the `wildAnimals` items will be only `fox`.

**Comment by mbknor** [comment]
Closed -- See comments in https://github.com/mbknor/mbknor-jackson-jsonSchema/pull/83 for more info
