### ISSUE TITLE
JsonTypeInfo.Id.MINIMAL_CLASS does not generate correct name for inner classes

### ISSUE THREAD

**Issue by luqasn** [mbknor/mbknor-jackson-jsonSchema#87]
It produces `.InnerClassName` instead of the correct (wrt Jackson) `.OuterClassName$InnerClassName`. This is because Jackson uses the package bath of the parent class and strips it from the child class full name instead of taking the `simpleName`:
```
String n = value.getClass().getName();
if (n.startsWith(_basePackagePrefix)) {
  // note: we will leave the leading dot in there
  return n.substring(_basePackagePrefix.length()-1);
}
```
See https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/jsontype/impl/MinimalClassNameIdResolver.java#L48

I have created https://github.com/mbknor/mbknor-jackson-jsonSchema/pull/86 in order to fix it.

Apart from the fix, it also contains some refactoring around type id generation.

**Comment by mbknor** [comment]
tx. I'm looking into it

**Comment by mbknor** [comment]
Version 1.0.32 is released and on its way to maven central
