### ISSUE TITLE
Handling NaN/extend injection mechanism

### ISSUE THREAD

**Issue by lordvlad** [mbknor/mbknor-jackson-jsonSchema#88]
We have different numeric fields in our objects, some of which allow NaN, some of which do not. Writing a schema by hand, it looks like this:
```json
"properties": {
  "allowsNaN": {
    "oneOf": [{"type": "string", "enum": ["NaN"]}, {"type": "number"}]
  }
}
```

Any chance we could get this autogenerated? A more challenging example would be something like

```java
@DecimalMin("0.0")
@Num(allowNaN=true)
@JsonPropertyDescription("Some property where NaN is an allowed value")
private double allowsNaN;
```

```json
"description": "Some property where NaN is an allowed value",
"properties": {
  "allowsNaN": {
    "oneOf": [{"type": "string", "enum": ["NaN"]}, {"type": "number", "minimum": 0.0}]
  }
}
```
Num is a custom bean validation annotation, with a validator that checks for NaN, infinity and min/max values.

Maybe we could have another property for `JsonSchemaInject` named `jsonFunction`. You'd need to supply a class that implements `Function<java.lang.reflect.Field, JsonNode>`, (analogous to `jsonSupplier` and `Supplier<JsonNode>`)  and using the field you could get all annotations and construct your own schema.

```java
@DecimalMin("0.0")
@Num(allowNaN=true)
@JsonPropertyDescription("Some property where NaN is an allowed value")
@JsonSchemaInject(merge=true, jsonFunction=NumInjector.class)
private double allowsNaN;


// NumInjector.java
class NumInjector implements Function<Field, JsonNode> {
  public JsonNode apply(Field f) {
    ObjectNode o = new ObjectMapper().createObjectNode();
    Num num = f.getAnnotation(n);
    if (num != null) {
      if (num.allowNaN()) {
        // construct {"oneOf": [{"type": "string", "enum": ["NaN"]}, {"type": "number"}]}
      } else {
        // construct {"type": "number"}
      }
    }
    return o;
  }
}
```

**Comment by mbknor** [comment]
To complicated feature-request. Please create PullRequest with suggested implementation if you are interested in getting the feature added.
