### ISSUE TITLE
Option to create schema that allows unknown (additional) properties on objects

### ISSUE THREAD

**Issue by ebolwidt-atlassian** [mbknor/mbknor-jackson-jsonSchema#90]
In many projects, we configure Jackson to ignore unknown properties. This allows for easy schema migration and zero-downtime production rollout of small schema changes where new properties are added.

Currently, this would only be possible by annotating each and every type to inject "additionalProperties: true" instead of the default "additionalProperties: false" on all objects.

Having one flag in the JsonSchemaConfig to change this for all types would be very useful. Proposing to name that flag "failOnUnknownProperties" like the Jackson `DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES`.

I've created a small PR that implements this change:

https://github.com/mbknor/mbknor-jackson-jsonSchema/pull/89

**Comment by mbknor** [comment]
Fixed in #89
