### ISSUE TITLE
Any plans to support newer drafts like the current 07 ?

### ISSUE THREAD

**Issue by ginccc** [mbknor/mbknor-jackson-jsonSchema#96]

**Comment by mbknor** [comment]
I'm not currently using this project in my day-to-day-work, so I do not have any need for draft 07.

But if you can highlight what the changes are (from 04 to 07), then maybe I'll have a look at it.

**Comment by ginccc** [comment]
Best is to read "Migrating from older drafts" here: https://json-schema.org/specification.html

**Comment by mbknor** [comment]
Thanks... I'll have a look at it
